CREATE DATABASE tv2pdeplazyhg5ny;

USE tv2pdeplazyhg5ny;

CREATE TABLE members (

id INTEGER(60) AUTO_INCREMENT NOT NULL,

user_Fname VARCHAR(60) NOT NULL,
user_Lname VARCHAR(60) NOT NULL,

user_email VARCHAR(255) NOT NULL,
user_password VARCHAR(255) NOT NULL,
user_image BLOB DEFAULT NULL,

cardio  VARCHAR(6) DEFAULT FALSE, 
strength VARCHAR(6) DEFAULT FALSE,
yoga  VARCHAR(6) DEFAULT FALSE,

morning  VARCHAR(6) DEFAULT FALSE,
midday VARCHAR(6) DEFAULT FALSE,
night VARCHAR(6) DEFAULT FALSE,

female  VARCHAR(6) DEFAULT FALSE,
male VARCHAR(6) DEFAULT FALSE,
no_pref VARCHAR(6) DEFAULT TRUE,

PRIMARY KEY (id)
);